/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> } 
 */
exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex('beans').del()
  await knex('beans').insert([
    {
      id: 1,
      name: "モカ（エチオピア）",
      bitterness: 2,
      acidity: 4,
      sweets: 4,
      richbody: 4,
      flavor: 5,
      about: "フルーティで華やかな香りのするやや小粒の豆が特徴です。嫌みの全くない酸味と軽い苦みが絶妙です。",
      yen: "税込 1,512円/200g",
      img: "beans.jpeg",
      url: "http://umapanera.com/?pid=50142269",
      score: 0
    },
    {
      id: 2,
      name: "トラジャ（アリオスト・カロシG-1）",
      bitterness: 4,
      acidity: 2,
      sweets: 3,
      richbody: 4,
      flavor: 5,
      about: "トラジャ王族の血を引くコーヒー。スパイシー、厚みのある酸味と丸みのボディ、長く続く余韻を楽しめます。",
      yen: "税込 1,728円/200g",
      img: "beans.jpeg",
      url: "http://umapanera.com/?pid=50142269",
      score: 0
    },
    {
      id: 3,
      name: "キリマンジャロ（エーデルワイスAA）",
      bitterness: 3,
      acidity: 4,
      sweets: 2,
      richbody: 4,
      flavor: 5,
      about: "エーデルワイス農園特有の柔らかな酸味を中心に、甘みと苦み、芳醇な香りを存分に楽しめます。",
      yen: "税込 1,620円/200g",
      img: "beans.jpeg",
      url: "http://umapanera.com/?pid=50142400",
      score: 0
    },
    {
      id: 4,
      name: "縁（ブレンド）",
      bitterness: 4,
      acidity: 1,
      sweets: 3,
      richbody: 4,
      flavor: 5,
      about: "４種類のスペシャリティ豆を使用したプレミアムブレンド。深い旨味が特徴。",
      yen: "税込 1,793円/200g",
      img: "beans.jpeg",
      url: "http://umapanera.com/?pid=56598653",
      score: 0
    },
    {
      id: 5,
      name: "コロンビア（ピコクリストバル）",
      bitterness: 2,
      acidity: 2,
      sweets: 4,
      richbody: 2,
      flavor: 4,
      about: "完熟したコーヒーチェリーのみ手摘みした甘味と苦味のバランスやマイルド感が素晴らしいスペシャルティ豆です。",
      yen: "税込 1,512円/200g",
      img: "beans.jpeg",
      url: "http://umapanera.com/?pid=50142123",
      score: 0
    },
    {
      id: 6,
      name: "夫婦（ブレンド）",
      bitterness: 2,
      acidity: 4,
      sweets: 4,
      richbody: 4,
      flavor: 4,
      about: "キリマンジャロ豆ベースの落ち着いた味わいが夜のひと時にピッタリ。",
      yen: "税込 1,447円/200g",
      img: "beans.jpeg",
      url: "http://umapanera.com/?pid=50142693",
      score: 0
    },
    {
      id: 7,
      name: "笑顔（ブレンド）",
      bitterness: 2,
      acidity: 2,
      sweets: 4,
      richbody: 3,
      flavor: 5,
      about: "モカ豆ベースの独特で深い香りがゆったりとした気持ちにしてくれる。",
      yen: "税込 1,447円/200g",
      img: "beans.jpeg",
      url: `http://umapanera.com/?pid=50142860`,
      score: 0
    },
    {
      id: 8,
      name: "健康（ブレンド）",
      bitterness: 2,
      acidity: 2,
      sweets: 2,
      richbody: 3,
      flavor: 4,
      about: "ブラジル豆ベースの苦味・酸味・甘味のバランスが良く、ガブガブ飲めます。",
      yen: "税込 1,534円/200g",
      img: "beans.jpeg",
      url: "http://umapanera.com/?pid=50142944",
      score: 0
    },
    {
      id: 9,
      name: "家族（ブレンド）",
      bitterness: 3,
      acidity: 3,
      sweets: 2,
      richbody: 3,
      flavor: 4,
      about: "苦味と甘味のバランスが良く、安定感のあるマイルドな味わいを楽しめる。",
      yen: "税込 1,404円/200g",
      img: "beans.jpeg",
      url: "http://umapanera.com/?pid=50142996",
      score: 0
    },
    {
      id: 10,
      name: "綾（ブレンド）",
      bitterness: 4,
      acidity: 2,
      sweets: 3,
      richbody: 4,
      flavor: 5,
      about: "トラジャ中心のやわらかい酸味と高貴な香りが特徴。まろやかで飲みやすい珈琲。",
      yen: "税込 1,620円/200g",
      img: "beans.jpeg",
      url: "http://umapanera.com/?pid=50528537",
      score: 0
    },
    {
      id: 11,
      name: "雅（ブレンド）",
      bitterness: 2,
      acidity: 2,
      sweets: 3,
      richbody: 3,
      flavor: 4,
      about: "落ち着きのある香りと深いコクは、食事の後やホッとしたい時にピッタリ。",
      yen: "税込 1,447円/200g",
      img: "beans.jpeg",
      url: "http://umapanera.com/?pid=50528595",
      score: 0
    },
    {
      id: 12,
      name: "グァテマラ（サンタバーバラ）",
      bitterness: 3,
      acidity: 4,
      sweets: 4,
      richbody: 3,
      flavor: 4,
      about: "過酷ともいえる標高で生育されるためわずかしか生産できません。逆境を越えたものだけが到達する真のコーヒーです。",
      yen: "税込 1,620円/200g",
      img: "beans.jpeg",
      url: "http://umapanera.com/?pid=55770095",
      score: 0
    },
    {
      id: 13,
      name: "アマレロブルボン",
      bitterness: 3,
      acidity: 4,
      sweets: 4,
      richbody: 4,
      flavor: 5,
      about: "アマレロは収穫量が極めて少ないブルボン種の中でもさらに希少な存在。UTZ認証も与えられた最高級豆。",
      yen: "税込 1,512円/200g",
      img: "beans.jpeg",
      url: "http://umapanera.com/?pid=57806993",
      score: 0
    },
    {
      id: 14,
      name: "ブラジル・ショコラ",
      bitterness: 3,
      acidity: 2,
      sweets: 4,
      richbody: 4,
      flavor: 4,
      about: "ビターチョコのような重厚感のある甘味を楽しめます。酸味の苦手な方へ特にオススメです。",
      yen: "税込 1,620円/200g",
      img: "beans.jpeg",
      url: "http://umapanera.com/?pid=133804987",
      score: 0
    }
  ]);
};
